context("run queues")

test_that("basic queue launch", {
    qname <- randomName("Q")
    bname <- randomName("B")
    q <- createQueue(name = qname, desc = "ici une description", clean = FALSE, folder = ".")
    q <- addBatch(object = q, path = "./batch1.R", name = bname)
    launch(q)
    Sys.sleep(1)
    qid <- getQID(name = qname)
    bid <- getBID(name = bname)
    expect_true(checkWQ(id=qid, name=qname))
    expect_true(checkWB(id=bid, name=bname, path = normalizePath("./batch1.R")))
})

test_that("basic queue with group & 2 batchs", {
    qname <- randomName("Q")
    bname1 <- randomName("B")
    bname2 <- randomName("B")
    gname  <- randomName("G")
    q <- createQueue(name = qname, group = gname, folder = ".", clean=F, desc = "queue test 2")
    q <- addBatch(object = q, path = "./batch1.R", name = bname1, waitBeforeNext=F, desc = "queue test2, batch1")
    q <- addBatch(object = q, path = "./batch1.R", name = bname2, endIfKO = FALSE, desc = "queue test2, batch2")
    launch(q)
    Sys.sleep(1)
    qid <- getQID(name = qname)
    bid1 <- getBID(name = bname1)
    bid2 <- getBID(name = bname2)
    expect_true(checkWQ(id=qid, name=qname, group=gname))
    expect_true(checkWB(id=bid1, name=bname1, group=gname, path = normalizePath("./batch1.R")))
    expect_true(checkWB(id=bid2, name=bname2, group=gname, path = normalizePath("./batch1.R")))
})

test_that("basic queue with batch with params", {
    qname <- randomName("Q")
    bname1 <- randomName("B")
    bname2 <- randomName("B")
    gname  <- randomName("G")
    q <- createQueue(name = qname, group = gname, folder = ".", clean=F, desc = "hello tout le monde")
    q <- addBatch(object = q, path = "./batch1.R", name = bname1, params = list(p1="hello",p2="bonjour",p3=3), desc = "test batch avec params")
    launch(q)
    Sys.sleep(1)
    qid <- getQID(name = qname)
    bid1 <- getBID(name = bname1)
    expect_true(checkWQ(id=qid, name=qname, group=gname))
    expect_true(checkWB(id=bid1, name=bname1, group=gname, path = normalizePath("./batch1.R")))
})

test_that("", {
    qname <- randomName("Q")
    bname1 <- randomName("B")
    bname2 <- randomName("B")
    bname3 <- randomName("B")
    gname  <- randomName("G")
    q <- createQueue(name = qname, group = gname, folder = ".", clean=F, desc = "q desc")
    q <- addBatch(object = q, path = "./batch1.R", name = bname1, desc = "desc1")
    q <- addBatch(object = q, path = "./batch1.R", name = bname2, desc = "desc2")
    q <- addBatch(object = q, path = "./batch1.R", name = bname3, desc = "desc3")
    launch(q)
    Sys.sleep(1)
    qid <- getQID(name = qname)
    bid1 <- getBID(name = bname1)
    expect_true(checkWQ(id=qid, name=qname, group=gname))
    expect_true(checkWB(id=bid1, name=bname1, group=gname, path = normalizePath("./batch1.R")))
})
